cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'neovim/neovim'

cask 'alfred'
cask 'dash'
cask 'flux'
cask 'font-source-code-pro-for-powerline'
cask 'google-chrome'
cask 'iterm2-nightly'
cask 'postgres'
cask 'spotify'

brew 'ack'
brew 'bash-completion'
brew 'ctags'
brew 'fzf'
brew 'git'
brew 'hub'
brew 'node-build'
brew 'nodenv'
brew 'neovim'
brew 'neovim/neovim/neovim'
brew 'python'
brew 'python3'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'yarn'
